#+TITLE: Surface Area and Porous Material Characterization
#+SUBTITLE: Notes from Martin Thomas' Short Course
#+AUTHOR: Rohit Goswami\textsc{\scriptsize\ MInstP AMIChemE AMIE}
# This should not be altered
#+OPTIONS: toc:nil title:nil
# I need the footnotes to be inlined
#+STARTUP: fninline

#
# LaTeX Stuff (from eisvogel https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex)
#

#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [12pt,a4paper,oneside,headinclude]

#+LATEX_HEADER: \PassOptionsToPackage{unicode=true}{hyperref}
#+LATEX_HEADER: \PassOptionsToPackage{hyphens}{url}
#+LATEX_HEADER: \PassOptionsToPackage{dvipsnames,svgnames*,x11names*,table}{xcolor}


#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage{amssymb,amsmath}
#+LATEX_HEADER: \usepackage{physics}
#+LATEX_HEADER: \usepackage{ifxetex,ifluatex}
#+LATEX_HEADER: \usepackage{fixltx2e} % provides \textsubscript
#+LATEX_HEADER: \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage{textcomp} % provides euro and other symbols
#+LATEX_HEADER: \else % if luatex or xelatex
#+LATEX_HEADER: \usepackage{unicode-math}
#+LATEX_HEADER: \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
#+LATEX_HEADER: \fi
#+LATEX_HEADER: % use upquote if available, for straight quotes in verbatim environments
#+LATEX_HEADER: \IfFileExists{upquote.sty}{\usepackage{upquote}}{}
#+LATEX_HEADER: % use microtype if available
#+LATEX_HEADER: \IfFileExists{microtype.sty}{%
#+LATEX_HEADER: \usepackage[]{microtype}
#+LATEX_HEADER: \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
#+LATEX_HEADER: }{}
#+LATEX_HEADER: \IfFileExists{parskip.sty}{%
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: }{% else
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{6pt plus 2pt minus 1pt}
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:             pdftitle={Surface Area and Porous Material Characterization},
#+LATEX_HEADER:             pdfauthor={Rohit Goswami},
#+LATEX_HEADER:             pdfborder={0 0 0},
#+LATEX_HEADER:             breaklinks=true}
#+LATEX_HEADER: \urlstyle{same}  % don't use monospace font for urls

#+LATEX_HEADER: \usepackage{longtable,booktabs}
#+LATEX_HEADER: % Fix footnotes in tables (requires footnote package)
#+LATEX_HEADER: \IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
#+LATEX_HEADER: \usepackage{graphicx,grffile}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
#+LATEX_HEADER: \def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: % Scale images if necessary, so that they will not overflow the page
#+LATEX_HEADER: % margins by default, and it is still possible to overwrite the defaults
#+LATEX_HEADER: % using explicit options in \includegraphics[width, height, ...]{}
#+LATEX_HEADER: \setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
#+LATEX_HEADER: \setlength{\emergencystretch}{3em}  % prevent overfull lines
#+LATEX_HEADER: \providecommand{\tightlist}{%
#+LATEX_HEADER:   \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
#+LATEX_HEADER: \setcounter{secnumdepth}{0}
#+LATEX_HEADER: % Redefines (sub)paragraphs to behave more like sections
#+LATEX_HEADER: \ifx\paragraph\undefined\else
#+LATEX_HEADER: \let\oldparagraph\paragraph
#+LATEX_HEADER: \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
#+LATEX_HEADER: \fi
#+LATEX_HEADER: \ifx\subparagraph\undefined\else
#+LATEX_HEADER: \let\oldsubparagraph\subparagraph
#+LATEX_HEADER: \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
#+LATEX_HEADER: \fi

#+LATEX_HEADER: % Make use of float-package and set default placement for figures to H
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \floatplacement{figure}{H}

#+LATEX_HEADER: \numberwithin{figure}{section}
#+LATEX_HEADER: \numberwithin{equation}{section}
#+LATEX_HEADER: \numberwithin{table}{section}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \@ifpackageloaded{subfig}{}{\usepackage{subfig}}
#+LATEX_HEADER: \@ifpackageloaded{caption}{}{\usepackage{caption}}
#+LATEX_HEADER: \captionsetup[subfloat]{margin=0.5em}
#+LATEX_HEADER: \AtBeginDocument{%
#+LATEX_HEADER: \renewcommand*\figurename{Figure}
#+LATEX_HEADER: \renewcommand*\tablename{Table}
#+LATEX_HEADER: }
#+LATEX_HEADER: \AtBeginDocument{%
#+LATEX_HEADER: \renewcommand*\listfigurename{List of Figures}
#+LATEX_HEADER: \renewcommand*\listtablename{List of Tables}
#+LATEX_HEADER: }
#+LATEX_HEADER: \@ifpackageloaded{float}{}{\usepackage{float}}
#+LATEX_HEADER: \floatstyle{ruled}
#+LATEX_HEADER: \@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
#+LATEX_HEADER: \floatname{codelisting}{Listing}
#+LATEX_HEADER: \makeatother

#+LATEX_HEADER: \usepackage[dvipsnames,svgnames*,x11names*,table]{xcolor}
#+LATEX_HEADER: \definecolor{listing-background}{HTML}{F7F7F7}
#+LATEX_HEADER: \definecolor{listing-rule}{HTML}{B3B2B3}
#+LATEX_HEADER: \definecolor{listing-numbers}{HTML}{B3B2B3}
#+LATEX_HEADER: \definecolor{listing-text-color}{HTML}{000000}
#+LATEX_HEADER: \definecolor{listing-keyword}{HTML}{435489}
#+LATEX_HEADER: \definecolor{listing-identifier}{HTML}{435489}
#+LATEX_HEADER: \definecolor{listing-string}{HTML}{00999A}
#+LATEX_HEADER: \definecolor{listing-comment}{HTML}{8E8E8E}
#+LATEX_HEADER: \definecolor{listing-javadoc-comment}{HTML}{006CA9}

#+LATEX_HEADER: \usepackage{pagecolor}
#+LATEX_HEADER: \usepackage{afterpage}
#+LATEX_HEADER: \setcounter{tocdepth}{3}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \setstretch{1.2}
#+LATEX_HEADER: \usepackage{csquotes}
#+LATEX_HEADER: \usepackage[font={small,it}]{caption}
#+LATEX_HEADER: \newcommand{\imglabel}[1]{\textbf{\textit{(#1)}}}
#+LATEX_HEADER: \definecolor{blockquote-border}{RGB}{221,221,221}
#+LATEX_HEADER: \definecolor{blockquote-text}{RGB}{119,119,119}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \newmdenv[rightline=false,bottomline=false,topline=false,linewidth=3pt,linecolor=blockquote-border,skipabove=\parskip]{customblockquote}
#+LATEX_HEADER: \renewenvironment{quote}{\begin{customblockquote}\list{}{\rightmargin=0em\leftmargin=0em}%
#+LATEX_HEADER: \item\relax\color{blockquote-text}\ignorespaces}{\unskip\unskip\endlist\end{customblockquote}}
#+LATEX_HEADER: \definecolor{heading-color}{RGB}{40,40,40}
#+LATEX_HEADER: \addtokomafont{section}{\color{heading-color}}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \renewcommand{\arraystretch}{1.3} % table spacing
#+LATEX_HEADER: \definecolor{table-row-color}{HTML}{F5F5F5}
#+LATEX_HEADER: \rowcolors{3}{}{table-row-color!100}

#+LATEX_HEADER: % Reset rownum counter so that each table starts with the same row color
#+LATEX_HEADER: \let\oldlongtable\longtable
#+LATEX_HEADER: \let\endoldlongtable\endlongtable
#+LATEX_HEADER: \renewenvironment{longtable}{\oldlongtable} {
#+LATEX_HEADER: \endoldlongtable
#+LATEX_HEADER: \global\rownum=0\relax}
#+LATEX_HEADER: \setlength{\parindent}{0pt}
#+LATEX_HEADER: \setlength{\parskip}{6pt plus 2pt minus 1pt}
#+LATEX_HEADER: \setlength{\emergencystretch}{3em}  % prevent overfull lines

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhead{}
#+LATEX_HEADER: \fancyfoot{}
#+LATEX_HEADER: \lhead{Surface Area and Porous Material Characterization}
#+LATEX_HEADER: \chead{}
#+LATEX_HEADER: \rhead{\today}
#+LATEX_HEADER: \lfoot{Rohit Goswami \textsc{\scriptsize\ MInstP AMIChemE AMIE}}
#+LATEX_HEADER: \cfoot{}
#+LATEX_HEADER: \rfoot{\thepage}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0.4pt}
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0.4pt}


#+LATEX_HEADER: % When using the classes report, scrreprt, book,
#+LATEX_HEADER: % scrbook or memoir, uncomment the following line.
#+LATEX_HEADER: %\addtokomafont{chapter}{\color{heading-color}}


# Nicer Fonts
# #+LATEX_HEADER: \usepackage{xunicode}
# #+LATEX_HEADER: \usepackage{xltxtra}
# #+LATEX_HEADER: \usepackage[protrusion=true,final]{microtype}
# #+LATEX_HEADER: \usepackage{mathspec}
# #+LATEX_HEADER: \defaultfontfeatures{Mapping=tex-text}
# #+LATEX_HEADER: \setromanfont[Ligatures={Common}, Numbers={OldStyle}]{Hoefler Text}
# #+LATEX_HEADER: \setsansfont[Scale=0.9]{Helvetica Neue}
# #+LATEX_HEADER: \setmonofont[Scale=0.8]{Courier}
# #+LATEX_HEADER: \newfontfamily\scfont[Scale=1.2]{Minion Pro}

#+LATEX_HEADER: \usepackage[default]{sourcesanspro}
#+LATEX_HEADER: \usepackage{sourcecodepro}

# Wider Text
# #+LATEX_HEADER: \usepackage[textwidth=7in,textheight=9in]{geometry}
#+LATEX_HEADER: \usepackage[margin=2.5cm,includehead=true,includefoot=true,centering]{geometry}

\begin{titlepage}
\newgeometry{left=6cm}
\definecolor{titlepage-color}{HTML}{06386e}
\newpagecolor{titlepage-color}\afterpage{\restorepagecolor}
\newcommand{\colorRule}[3][black]{\textcolor[HTML]{#1}{\rule{#2}{#3}}}
\begin{flushleft}
\noindent
\\[-1em]
\color[HTML]{ffffff}
\makebox[0pt][l]{\colorRule[ffffff]{1.3\textwidth}{1pt}}
\par
\noindent

{ \setstretch{1.4}
\vfill
\noindent {\huge \textbf{\textsf{Surface Area and Porous Material Characterization}}}
\vskip 1em
{\Large \textsf{Short Course Notes}}
\vskip 2em
\noindent
{\Large \textsf{\MakeUppercase{Rohit Goswami,\textsc{\scriptsize\ MInstP AMIChemE AMIE}}}
\vfill
}

\textsf{\today}}
\end{flushleft}
\end{titlepage}
\restoregeometry

\tableofcontents
\newpage

# Start Here

* Lec I: Physisorption and Basic Measurements
Dr. Martin A. Thomas is the speaker for the day.
- Surface Area
- Catalysis
** Essential Techniques
- Surface area
- Pore size distribution
- Catalyst active area/dispersion
- TPR and other flow materials
** Surface Area
For the purposes of this scale, the geometric extent of the interface between
two materials in any phase would be the surface area. Surface area measurement
is useful for a variety of situations:
- Reveals an excess of fines that PSA cannot
- Can distinguish between different morphologies of similar size
- Can follow the generation of particle-particle bonds
  Typically van-der-waals but under certain temperature and pressure can cause sintering which would be "true" bonds in
terms of ionic and covalent bonds.
- Temporal morphological stability
- Confirms brittle fracture under compression
- Tighter control on specifications of raw materials to avoid surprises during
  later processing
- Can explains unxepected dissolution behavior
*** Discussion
The PSA (particle size analysis) is not always of much use. Even the 90%
median measures may miss out on certain complexities which broaden or alter the
spread without changing the median measures. The surface area considerations are
significant then. Of course the surface area is most important when one
considers porous materials. The surface as defined here extends through the bulk
of the material due to the porosity.
"Stickiness" is simply when the gravitational pull on the particle cannot
overcome the molecule's attraction to the surface. The surface free energy is
the amount avaliable for work. At the surface when the surface free energy
increases, there is an increase in the dissolution rate. When the surface area
decreases, the commiserate reduction in the surface free energy reduces
dissolution while increasing strength. Especially when there is a liquid, the
surface area is a very good measure of the liquid lost to the porosity.

** Dissolution rate
The Noyes-whitney or the nerst-brunner equation is used for the dissolution rate:

$$\frac{dW}{dt}=\frac{DA(C_S-C)}{L}$$
** Pore Size
The pore size distribution is inversely proportion to the fluid adsorption.
*** Hierarchical Pore Stuctures
Inspired by the lungs, the idea is to have progressively larger surface area
with increasing depth.
*** Catalyst Turnover
A general trend in the turnover, that is, the number of reactions which may
occur at a reactive site is seen to be strongly correlated to the pore-size.
** Gas Adsorption
This is the only technique which directly mesasures and quantifies the surface
area accurately. Hg intrusion is important too since it covers a wider range but
then it isn't a really direct measure.
The only biase is the sieving effect.

IUPAC definitons:
- Micropore is less than 2nm
- Mesopore is between two to fifty nm
- Macropores are larger than 50nm
*** Calculation mMethods
A small pore version is a stronger absorber. The pore causes the adsorption
force to "focus" in a sense. LJ potential energy analysis shows that the
entering molecules "see" more than one surface during adsorption. The isotherm
is used to directly measure the gas interacting with a surface and within the pore.

Gas adsorption goes upto 500nm. The BJH is a classical method based on the
Kelvin equation. There are also DFT kernel methods.
Smaller pore has lower pore filling pressure. The pore filling pressure is used
to calculate the pore size and the extent of the surface. This also means we can
get the pore volume. The pore size distribution is a volume distribution, not a
spatial distribution.
**** Basics
We need to remember to have the saturation pressure in mind for physisorption.
*** Total Physisorption
This analyzes extensive ranges of physical properties. The BET surface area is
the Brunnet-Emmet-Teller method. Typically the BET surface area is one of the
total area. The T plot method is used in the multi-layer portion and is used to
get the micropore distribution. The mesopore size distribution shows a hysteris
curve from which information about the pore structure can be *qualitatively* obtained

** Flow Analysis
Cooling is important to get the information required. The desorption peak is
used to measure BET areas due to quick heating of the sample and get a sharper peak.
*** Vacuum Volumetric Principle
This is a manometric principle. The point is still to obtain the isoterm. So the
construction involves a sample cell, cooled with liquid nitrogen. There is a
evacuation system to ensure that the full isotherm can be obtained. The
temperature (measured), volume (calibrated), and the pressure (controlled) in the manifold, the ideal
gas law can be used to figure out the amount absorbed.

Typically for surface area and pore size analysis:
- Nitrogen at 77K. For micropore size distribution for microporous carbons will
  take upto 2 hours. For zeolites, argon at 87K is about twice as fast.
- Argon at 87K. Is recommended by the IUPAC. This is very good for micropores
  because it is monoatomic, no orientation issues, is non-polar and inert
  (surface changes have no effect). Ar (87K) kinetics are faster than nitrogen
  at 77K (shorter equilibration times).
- CO$_2$ at 273K. The polarization makes it unsuitable for zeolites. It is
  typically used for narrow pores in microporous carbons. Can get a micropore
  carbon in a few hours (4 to 6). A lot of this is because of the increased temperature.
- Krypton 77K or 87K for very low temperatatures since it is really expensive.
  Used when Nitrogen cannot be used.
** Practical Rules of Thumb
*** Sample Cell Selection
The cell which minimizes the void volume is the right one. Overfilling risks
elutriation. Larger void volumes will cause a loss in precision.
 The smallest bulb which accomodates the optimal TSA but no more than two thirds full.
*** Minimize negative impact of cold volume
Coolant level controlled at the top creates a large cold zone. Coolant level
controlled at the bottom causes a smaller cold zone.
*** Sample Preparation
Degassing is normally done by heating under flow, or by using a vacuum. The highest temperature which
will not ruin the material is what should be used. Ensure that the substance
does not degrade. Flow methods will not be very good in some cases, namely
because there is a water molecule in the pore which has to come out slowly.
*** Degassing Time
The complete time is by experimentation. Typically its sixteen hours, which is
considered to be overnight. Samples that require low temperatures generally
require the longest outgas times.
*** P/Po Range Selection
The multi-point BET is lower than the single point BET.
*** Micropore challenges
Typically there are many extended range micropore stations each with a dedicated
manifold and a complete set of transducers.
*** Data Reduction
Micropores are upto the leveling out of the isotherms. Multilayer use the Tplot.
The mesopore region is beyond that. Right at the top end is where the gas
absorbs into the interparticle space. This is essentially a feature of the
undefined interparticle sizes.

IUPAC pores:
- Pores smaller than 2nm
- Supermicropores 0.7 to 2nm
- Ultramicropores are less than 0.7nm

The density of the absorbed gas is estimated to figure out geometric aspects of
the pore being studied. Type four regions are essentially the macropore range.
For micropores you need the data from ten to the power minus ten to see the
micropore filling.

For different P/Po the same micropores may be observed. Nitrogen's strong
quadrupole shifts the pore filling to much lower P/Po. DFT can correct somewhat,
but argon is much more reliable.
Micropores usually have a turbo pump and a diaphragm pump.

The take away is that pore filling pressure is directly proportional to the pore
size diameter.

- Nitrogen is great for good for SA, Mesopore and total pore volume but not for
micropore sizes.
- Argon is recommended in all cases greater than 0.5nm because the gases listed
  are least affected by surface chemistry.
- Carbon dioxide cannot do anything other

** DFT
Lowell, sheilds thomas and Thommes. Characterization of porous solids and
powders.
Neimark, Ravikovitch, Thammes, Carbon (2009)
Thommes Cychosz, Neimark

NLDFT skernel of metastable isotherms take into accound delays which may occur.

M. Thommes. In Nanoporous Materials Science and engineering

When there is a network defect, then there are ink-bottle pores, M. Thommes, B.
Smarsly, M. Grenewold, Ravikovitch, Neimark, Langmuir 2001.

#+BEGIN_QUOTE
Rutgers University under Alex Neimark carries out much of the academic DFT calculations
#+END_QUOTE

#+BEGIN_QUOTE
For these systems, though earlier studies have used MC, DFT is actually faster.
#+END_QUOTE

#+BEGIN_QUOTE
The temperature effects (local heating due to the exothermic nature of
adsorption) does cause a delay for accuracy, that is, the system is to be
equilibrated and cannot be hastened.
#+END_QUOTE


* Lec 2: Chemisorption
This is also known asn reactive gas adsorption. This is typically used to
quantify the number of reactive sites. Silver catalysts are low dispersion.

#+caption: Chemisorption
| Feature                 | Analysis          |
| Active Metal Area       | TPR               |
| Dispersion              | TPO               |
| Crysallite size         | TPD               |
| Acid site concentration | Activation Energy |
| Heat of adsorption      |                   |
|-------------------------+-------------------|

The crystallite size is typically not the true size, except in some special
systems. Protonated zeolites have acidic sites, and that is the visual metric
used expressed as the amount of gas. There is no real conversion as there is no
real surface area calculation.

A wetting syste is such that the metal to the support affinity is higher than
that of the metal-metal affinity. There may be steric hinderance, but
essentially the wetting systems tend towards to spreading out over the surface.
When there is less dispersion, the metal will tend to coagulate in lumps, which
will cause some of the atoms to be not be accessible for reactions.

Physorption areas and chemisorption areas are different. The cross sectional
area is used for the physisorption, that is some 16 angstrom. The metal area
does not use the area of the adsorbed gas. It uses the size of the absorbing
site. The internuclear distance for the metal can also be used. The projected
area estimates can vary.

Forming a chemical bond does not require cryogenic conditions. Hydrogen is very
popular since it chemisorbs to a lot of metals. Since it forms a hydride
sometimes, there is some "solubility" in the metal, so the adsorbed gas may not
actually be localized on the surface. Typically where hydride formation is an
issue, CO is used. Twice as many CO moleculas are adsorbed compared to H_2 for
Platinum.

#+caption: Metals and Reactive Gases for Chemisorption
| Metal | Reactive gas | Comment                                                 |
| Pt    | hydrogen, CO | Twice as many Co as H_2                                 |
| Pd    | CO           | Pd forms bulk hydrides, i.e. not limited to the surface |
| Ni    | Hydrogen     | Ni forms carbonyls, not limited                         |
| Fe    | Hydrogen     | Fe forms carbonyles, not limit to the surface           |
| Ag    | Oxygen       | At elevated temperatures                                |
|-------+--------------+---------------------------------------------------------|

Ni may also be volatile enough to form a Ni mirror somewhere cooler.

** Stochiometry
The number of metal atoms per gas molecule. The instrument can measure how much
gas is adsorbed. Normally it is assumed that hydrogen dissociates on the
surface, so one hydrogen molecule will dissociate over two metal atoms. In some
cases in the literature they use the number of atoms reating per molecule, so
that is half. When we consider CO, it may be one or bridged, and therefore two.
At low pressures of Co, the bridged system is more likely, so as the pressure
increases, it is reasonable to assume a steric geometry of one.
** Setup
The volumetric version of the equipment is usually the same as that used for
physisorption.

# Local Variables:
# after-save-hook: haozeke/org-save-and-export-pdf
# End:
